name: wanandroid_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # custom
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1

  # Basic
  oktoast: ^3.4.0
  flutter_screenutil: ^5.9.0
  connectivity_plus: ^6.0.2
  dio: ^5.4.3+1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  go_router: ^13.2.3
  flutter_smart_dialog: ^4.9.6
  flutter_svg: ^2.0.10+1
  html: ^0.15.4
  html_unescape: ^2.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  package_info_plus: ^7.0.0
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0
  permission_handler: ^11.3.1
  event_bus: ^2.0.0
  crypto: ^3.0.3
  device_info_plus: ^10.1.0
  extended_image: ^8.2.0
  easy_refresh: ^3.3.4
  flutter_settings_ui: ^3.0.1
  tdesign_flutter: ^0.1.4
  hive: ^2.2.3
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  card_swiper: ^3.0.1
  get_it: ^7.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  freezed: ^2.4.7
  custom_lint:
  riverpod_lint:
  json_serializable: ^6.7.1
  go_router_builder: ^2.4.1
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1
  retrofit_generator: ^8.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/json/
    - assets/images/


flutter_intl:
  enabled: true