name: wanandroid_flutter_bloc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # custom
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  card_swiper: ^3.0.1 # 轮播图

  # Basic
  oktoast: ^3.4.0
  connectivity_plus: ^6.0.2
  flutter_screenutil: ^5.9.0 #屏幕适配
  go_router: ^13.2.3
  flutter_smart_dialog: ^4.9.6
  intl: ^0.18.1
  logger: ^2.2.0 #日志
  package_info_plus: ^7.0.0
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  flutter_bloc: ^8.1.5 #状态管理
  dio: ^5.4.3+1 #网络库
  easy_refresh: ^3.3.5+1
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.1
  webview_flutter_wkwebview: ^3.13.0
  permission_handler: ^11.3.1
  event_bus: ^2.0.0
  crypto: ^3.0.3
  device_info_plus: ^10.1.0
  extended_image: ^8.2.0
  tdesign_flutter: ^0.1.4
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  collection: ^1.18.0
  shared_preferences: ^2.2.3 #持久化
  status_bar_control: ^3.2.1 # 状态栏管理
  get_it: ^7.6.8
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  go_router_builder: ^2.4.1
  retrofit_generator: ^8.1.0

flutter:

  uses-material-design: true

flutter_intl:
  enabled: true