name: wanandroid_flutter_bloc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0 #屏幕适配
  logger: ^2.2.0 #日志
  cached_network_image: ^3.3.1 #图片缓存
  fluro: ^2.0.5 #路由管理
  fluttertoast: ^8.2.5 #吐司
  flutter_bloc: ^8.1.5 #状态管理
  flutter_easyloading: ^3.0.5 # loading
  dio: ^5.4.3+1 #网络库
  pull_to_refresh: ^2.0.0 #下拉刷新，上拉加载
  easy_refresh: ^3.3.5+1
  card_swiper: ^3.0.1 # 轮播图
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.1
  webview_flutter_wkwebview: ^3.13.0
  flutter_staggered_grid_view: ^0.7.0
  collection: ^1.18.0
  shared_preferences: ^2.2.3 #持久化
  status_bar_control: ^3.2.1 # 状态栏管理
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true